index:
   path: /
   controller: App\Controller\DefaultController::index

# hello:
#   path: /hello
#   controller: App\Controller\HelloController::hello

# helloName:
#   path: /hello/{name}
#   controller: App\Controller\HelloController::helloName